import Link from 'next/link';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const menuItem = (url: string, title: string, className?: string) => (
    <div className={`bg-black text-zinc-100 py-2 px-3 rounded-lg  ${className}`}>
      <Link href={url}>{title}</Link>
    </div>
  );
  return (
    <html lang="en">
      <body className="container mx-auto bg-white text-zinc-900 px-2">
        {/* Header */}
        <div className="md:inline-flex  w-full py-[10px] justify-between">
          {menuItem('/', 'Home', 'bg-transparent text-lg text-blue-300')}
          <div className="inline-flex  space-x-3 items-end  justify-end">
            {menuItem('/dashboard', 'Dashboard')}
            {menuItem('/setting', 'Setting')}
            {menuItem('/calculator', 'Calculator')}
            {menuItem('/search', 'Search Github')}
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
